ItsRoy69/DocTalk

CONTRIBUTING.md, client/package-lock.json, client/src/App.jsx, client/src/Pages/UserRegister.jsx, package-lock.json
- **I <your name here> have worked for <#4>**
- **My pull request closes <#4>**
---
=> Added User Registration page

client/src/App.jsx, client/src/Pages/Doctorcontact.jsx, client/src/Pages/Doctorinfo.jsx, client/src/components/Services/Services.css, client/src/components/Services/Services.jsx, client/src/context/Docstate.jsx, client/src/service/DoctalkApi.js
- **I  Alagu  have worked for #11  under <Opensource Event>**
---
=> Fix:Add doctor section

client/package-lock.json, server/index.js, server/models/User.js, server/package-lock.json, server/package.json, server/routes/user.js, server/utils/bcrypt.js
- **I <your name here> have worked for <issue number> under <Opensource Event>**
**signup**
**login**
---
=> fix : added user registration and login (backend)

client/src/components/Heading.js, client/src/pages/Home.js, client/src/styles/Heading.css, client/src/styles/Navbar.css
=> added heading

client/package-lock.json, client/src/components/Footer.js, client/src/styles/Footer.css
- **I Nitin have worked for #5 **
**I accept the fact that I have followed the guidelines and have not copied the codes from around the internet**
- **My pull request closes #5 **
**Here are the pictures of changes that I have made 🔽**
---
=> Added new Footer

client/src/pages/Home.js, client/src/styles/Home.css
- **I Nitin have worked for #39**
- **My pull request closes #39 **
---
=> Added About section for home page

client/src/pages/Home.js, client/src/styles/Home.css
- **I Nitin have worked for #41 **
- **My pull request closes #41 **
---
=> Added contact section

client/src/pages/DonatePlasma.js, client/src/styles/DonatePlasma.css
- **I <Sarrene> have worked for <#51> under <DocTalk>**
- **My pull request closes <#51>**
**Here are the pictures of changes that I have made 🔽**
---
=> Create Donate Plasma Page

client/src/components/Footer.js, client/src/styles/Footer.css
- **I Rohit Roy have worked for #42 **
[X]: <> (This is a comment, it will not be included)
**I accept the fact that I have followed the guidelines and have not copied the codes from around the internet**
- **My pull request closes #42 **
---
=> Fix: Enhancement of Welcome Page !

client/package-lock.json, client/src/pages/RegAmbulance.js, client/src/styles/RegAmbulance.css
Registration of Ambulance Supplier
- **I <Suman373> have worked for <64> under <Opensource Event>**
**I accept the fact that I have followed the guidelines and have not copied the codes from around the internet**
- **My pull request closes <#64>**
---
=> Ambulance reg page added

client/package-lock.json, client/package.json, client/src/App.js, client/src/components/Navbar.js, client/src/components/ScrollToTop.js, client/src/pages/Home.js, client/src/pages/PlasmaDonor.js, client/src/styles/Navbar.css
- **I Rajarshi Biswas have worked for #67**
- **My pull request closes #67**
**Here are the proof of changes that i have made 🔽**
https://user-images.githubusercontent.com/72081132/181485034-f8826758-b688-4f36-ac71-a9612c89aa4d.mp4
https://user-images.githubusercontent.com/72081132/181485081-b2efb940-1958-4b84-bfba-be443ca4284c.mp4
---
=> Fix: Navbar link section for both desktop and mobile view

client/src/pages/Home.js, client/src/styles/Home.css
#69  📐
- **I Rohit Roy have worked for #69 **
[X]: <> (This is a comment, it will not be included)
---
=> fix: Updated AboutUs corner !

client/src/components/Navbar.js, client/src/pages/RegMedicine.js, client/src/pages/RegOxygenSupply.js, client/src/styles/RegMedicine.css
54
- **I <Suman> have worked for <54> under <Opensource Event>**
- **My pull request closes <#54>**
---
=> #54 :  Medicine Supplier Page

client/src/styles/Home.css
74
- **I <your name here> have worked for <issue number> under <Opensource Event>**
Suman373
#74
- **My pull request closes <#74>**
---
=> #74 : Fixed  button size for banner and hover effects for services section

client/src/components/Footer.js, client/src/styles/Footer.css
#82 Adjust the size of an image on footer
Hello I am dnyanesh, I have worked for issue #82
- **My pull request closes #82**
---
=> Image aligned properly in Mobile View

client/package-lock.json, client/package.json, client/src/index.js, client/src/styles/Home.css
- **I Rohit Roy have worked for #89  under personal repository**
[X]: <> (This is a comment, it will not be included)
- **My pull request closes #89 **
---
=> Fix > High Contrast Shadow/BoldText > [Get In Touch] Button

client/src/data/oxygenSupplier.js, client/src/styles/OxygenSupplier.css
- **I Rohit Roy have worked for #100 under Personal project**
[X]: <> (This is a comment, it will not be included)
- **My pull request closes #100 **
---
=> Created Oxygen Supplier Page !

client/src/pages/DonatePlasma.js, client/src/styles/DonatePlasma.css
- I **Vansh Baghel** have worked for **issue #106** of fixing the donate page.
1. Added on click effect on input.
2. Added icons & fixed the size.
3. Fixed the placeholder text.
4. Aligned the header in the center.
5. Added logic for valid number input.
6. Changed the input text and border color.
7. Made all input fields as required.
8. Removed the scroll buttons from the input type number.
=> Donate page changes

client/package-lock.json, client/src/pages/PlasmaDonor.js, client/src/styles/plasmadonors.css
- **I Satyam have worked for #120  under HacktoberFest**
---
=> Fixed Donors page

client/src/pages/HospitalBed.js
UI Issue with rendering images of hostpital beds
- **I Aarthi Suresh Kumar have worked for #140  under Hacktoberfest**
- My pull request closes #140 
---
=> Fix: UI Issue with rendering images of hostpital beds

rules/Setup.md
- **I <your name here> have worked for <issue number> #142  under <Opensource Event>**
---
=> Update Setup.md added docker setup

client/src/components/Navbar.js, client/src/pages/Home.jsx, client/src/styles/Navbar.css
- **I Ali have worked to improve the navbar of the website**
- Switched Contact & Signup links places
- Added Navbar background
- Made navbar fixed to be easier to navigate through the website
- Worked on the design
- Added auto-close navbar after clicking a link in the same page
**- Only added id="home" in Home.jsx file (line 55), prettier made other changes improving the structure of the code.**
---
=> Improve Navbar

client/src/components/OxygenSupply.js, client/src/pages/OxygenSupplier.js, client/src/styles/OxygenSupplier.css
Oxygen Supplier page is not rendering as expected
- **I Aarthi Suresh Kumar have worked for #116  under Hacktoberfest**
- **My pull request closes #116 **
With multiple suppliers
Media responsive - 1
Media responsive - 2
!
=> Fix: Oxygen Supplier page is not rendering as expected

README.md
- **I AliFahed have worked for #149.**
- **My pull request closes #149**
---
=> Fix: Typos in README.md

client/src/components/Footer.js, package-lock.json
- **I Prakhar Pandey have worked for #160 **
**I accept the fact that I have followed the guidelines and have not copied the codes from around the internet**
- **My pull request closes  #160 **
---
=> Added Github link

client/src/App.js, client/src/components/Loader.js, client/src/components/Navbar.js, client/src/pages/Home.jsx, client/src/styles/Home.css
Signed-off-by: Subham Bhattacharjee (mailto:subhambhttachariya03@gmail.com)
On Mobile, the view header section text are too close.
New Feature: Adding a Lazy loading feature.
Issue closed: https://github.com/ItsRoy69/DocTalk/issues/163
=> Adding Lazy loading feature and improve some small bugs. 

client/src/styles/plasmadonors.css
- I Prakhar have worked for issue #159 
- My pull request closes #159 
On hovering:
---
=> Added hover feature
